apiVersion: v1
kind: Service
metadata:
  labels:
    app: sharding-example
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: "sharding-example"
spec:
  ports:
  - name: management
    port: 8558
    protocol: TCP
    targetPort: 8558
  - name: remoting
    port: 2551
    protocol: TCP
    targetPort: 2551
  selector:
    app: sharding-example
  clusterIP: None
  publishNotReadyAddresses: true